version: 1.0.{build}
image:
- Visual Studio 2017
test: off
platform:
- x64
build:
  parallel: true
environment:
  matrix:
    - BUILD_MODE: Release
    - BUILD_MODE: Debug
build_script:
- cmake -G "Visual Studio 15 2017" -A "x64" -DCMAKE_SUPPRESS_REGENERATION=1
- set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmake --build . --config %BUILD_MODE% -- /v:m /m /logger:%MSBuildLogger%
- ctest
