name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  CIBW_BUILD: cp3?-*
  CIBW_SKIP: "*-win32 *-manylinux_i686"
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  MACOSX_DEPLOYMENT_TARGET: 10.14

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
  
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Prepare compiler environment for Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
